# Generated by Django 5.0.7 on 2024-12-03 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matatu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('plate_number', models.CharField(max_length=50, unique=True)),
                ('capacity', models.CharField(choices=[('14 Seater', '14 Seater'), ('33 Seater', '33 Seater'), ('52 Seater', '52 Seater')], default='33 Seater', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'In Maintenance')], default='active', max_length=20)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matatus', to='route.route')),
            ],
            options={
                'verbose_name': 'Matatu',
                'verbose_name_plural': 'Matatus',
            },
        ),
    ]
