# Generated by Django 4.2.7 on 2024-12-03 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('description', models.TextField(blank=True)),
                ('is_major_stop', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_order', models.PositiveIntegerField()),
                ('distance_from_start', models.DecimalField(decimal_places=2, max_digits=8)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matatu.route')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matatu.stop')),
            ],
            options={
                'ordering': ['stop_order'],
            },
        ),
        migrations.AddField(
            model_name='route',
            name='stops',
            field=models.ManyToManyField(through='matatu.RouteStop', to='matatu.stop'),
        ),
        migrations.CreateModel(
            name='FareRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_distance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_distance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fare', models.DecimalField(decimal_places=2, max_digits=6)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matatu.route')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matatu.farerule')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matatu.route')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matatu.stop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
