# Generated by Django 5.0.7 on 2024-12-06 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fare', '0002_alter_fare_fare_type_alter_fare_min_distance'),
        ('matatu', '0001_initial'),
        ('route', '0001_initial'),
        ('stop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matatu_Stages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=20)),
                ('fare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fare.fare')),
                ('matatu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matatu.matatu')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.route')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stop.stop')),
            ],
        ),
    ]
